name: Run test suite

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup V
        uses: vlang/setup-v@v1.4
        with:
          check-latest: false
          stable: true

      - uses: actions/checkout@v4
        with:
          path: clap

      - name: Run tests
        run: |
          mkdir -p ~/.vmodules
          ln -s $(pwd) ~/.vmodules/clap
          v test clap
